server:
  port: 2000

spring:
  cloud:
    gateway:
      routes:
        - id: userCommandApi
          uri: http://localhost:8081/api/v1/users
          predicates:
            - Path=/api/v1/users
        - id: userQueryApi
          uri: http://localhost:8082/api/v1/users/**
          predicates:
            - Path=/api/v1/users/**
        - id: bankaccCommandApi
          uri: http://localhost:9091/api/v1/bank-accounts
          predicates:
            - Path=/api/v1/bank-accounts